# Generated by Django 5.0.1 on 2024-01-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=100)),
                ('dop', models.DateField(max_length=20)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
    ]
