# Generated by Django 5.0.1 on 2024-01-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookde', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='dop',
            new_name='date_of_publication',
        ),
    ]
